version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todo-net

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - todo-net

volumes:
  pgdata:

networks:
  todo-net:
